# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import solarpipe_pb2 as solarpipe__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in solarpipe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonTrainerStub(object):
    """SolarPipe Python sidecar service.
    All large arrays are passed via file-based Arrow IPC (RULE-125), not inline proto.
    Training uses server-streaming RPCs to avoid deadline issues for long runs (ADR-011, RULE-061).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
                '/solarpipe.PythonTrainer/Train',
                request_serializer=solarpipe__pb2.TrainRequest.SerializeToString,
                response_deserializer=solarpipe__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.StreamTrain = channel.unary_stream(
                '/solarpipe.PythonTrainer/StreamTrain',
                request_serializer=solarpipe__pb2.TrainRequest.SerializeToString,
                response_deserializer=solarpipe__pb2.TrainProgress.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/solarpipe.PythonTrainer/Predict',
                request_serializer=solarpipe__pb2.PredictRequest.SerializeToString,
                response_deserializer=solarpipe__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.ExportOnnx = channel.unary_unary(
                '/solarpipe.PythonTrainer/ExportOnnx',
                request_serializer=solarpipe__pb2.ExportOnnxRequest.SerializeToString,
                response_deserializer=solarpipe__pb2.ExportOnnxResponse.FromString,
                _registered_method=True)


class PythonTrainerServicer(object):
    """SolarPipe Python sidecar service.
    All large arrays are passed via file-based Arrow IPC (RULE-125), not inline proto.
    Training uses server-streaming RPCs to avoid deadline issues for long runs (ADR-011, RULE-061).
    """

    def Train(self, request, context):
        """Unary: train a model. arrowIpcPath is a filesystem path to an Arrow IPC file.
        For long-running training, prefer StreamTrain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrain(self, request, context):
        """Server-streaming: emit progress events during training, then a final result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Unary: predict on new data. arrowIpcPath points to Arrow IPC feature file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportOnnx(self, request, context):
        """Export trained model dynamics network to ONNX (Neural ODE only). RULE-070.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=solarpipe__pb2.TrainRequest.FromString,
                    response_serializer=solarpipe__pb2.TrainResponse.SerializeToString,
            ),
            'StreamTrain': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrain,
                    request_deserializer=solarpipe__pb2.TrainRequest.FromString,
                    response_serializer=solarpipe__pb2.TrainProgress.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=solarpipe__pb2.PredictRequest.FromString,
                    response_serializer=solarpipe__pb2.PredictResponse.SerializeToString,
            ),
            'ExportOnnx': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportOnnx,
                    request_deserializer=solarpipe__pb2.ExportOnnxRequest.FromString,
                    response_serializer=solarpipe__pb2.ExportOnnxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'solarpipe.PythonTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('solarpipe.PythonTrainer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonTrainer(object):
    """SolarPipe Python sidecar service.
    All large arrays are passed via file-based Arrow IPC (RULE-125), not inline proto.
    Training uses server-streaming RPCs to avoid deadline issues for long runs (ADR-011, RULE-061).
    """

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solarpipe.PythonTrainer/Train',
            solarpipe__pb2.TrainRequest.SerializeToString,
            solarpipe__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/solarpipe.PythonTrainer/StreamTrain',
            solarpipe__pb2.TrainRequest.SerializeToString,
            solarpipe__pb2.TrainProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solarpipe.PythonTrainer/Predict',
            solarpipe__pb2.PredictRequest.SerializeToString,
            solarpipe__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportOnnx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solarpipe.PythonTrainer/ExportOnnx',
            solarpipe__pb2.ExportOnnxRequest.SerializeToString,
            solarpipe__pb2.ExportOnnxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
